### ISSUE TITLE
Tron signed message

### ISSUE THREAD

**Issue by fbsobreira** [TRON-US/tronweb#49]
https://github.com/TRON-US/tronweb/blob/027817d54fca8a4189f4f25aca291cc9415f6e43/src/lib/trx.js#L7

Signed message suppose to follow '\x19TRON Signed Message:\n< message length >< message >'
But here is taken as default size of 32, which may work for most of the cases that have message as a 32-bytes hash

**Comment by sullof** [comment]
I think after this issue we talked about it on Discord.
While makes sense that the size can be different that 32, in TronWeb you sign all the time a Sha3 hash of something, which is always 32 bytes long. 
Moving from `\x15` to `\x19` would makes sense but, in both cases, the problem is how to change that without breaking the compatibility with most apps. I don't think that right now that is solvable, so, we will keep the initial mistake.
